### ISSUE TITLE
Shared Database

### ISSUE THREAD

**Issue by zDEFz** [helgovic/Broadlink-for-Windows#1]
You said in your description that you have a shared database. I'd like to contribute. However, you'd have to host it somewhere. But perhaps it's a better idea to just use github for it. I have some devices myself captured...

**Comment by helgovic** [comment]
If you captured the devices using this app, just click Settings->Share devices. If not see "Database specs"

**Comment by zDEFz** [comment]
> If you captured the devices using this app, just click Settings->Share devices. If not see "Database specs"

I do not even get an UI. I do not know what you talk about.  I thought one had to run your service hidden and then use the terminal.

Anyhow. Such database is supposed to be open source I expect a separate website with a database for users to connect to and enter new data.

**Comment by helgovic** [comment]
Did you install and run the app?

**Comment by helgovic** [comment]
I do not know what you mean by " run your service hidden and then use the terminal". Winbroadlink is a Windows app

**Comment by zDEFz** [comment]
> 

Probably been the firewall. Anyhow, then WinBroadlink isnt what I thought it was anyways. I had issues getting the python broadlink_cli to run under Windows. It works on Linux... I don't think I can give it another go on Windows unless its the CLI.

If it's a app, it has a GUI. If not, its CLI. The first page on the README doesnt provide a screenshot. In the end I see commandline options.
However, the UI didnt show ever up for me, so I went for the CLI and execution / passing commandline parameters did not do anything either. I have the slight suspicion that my firewall/AV is blocking it silently or something else is broken.

I must not provide logs this time around.

**Comment by helgovic** [comment]
The gui has to be running when executing cli commands. After you run the setup program from the install folder, you should be able to launch the gui from the start menu.
